### PR TITLE
front end page

### PR DESCRIPTION
**Pull request by gyr5098**
I add some front page, including 404.js, AnalyseArticle.js , EvidenceList.js ,Home.js ,ModerateArticle.js ,SearchingArticle.js , Submit-Article.js. And adding some dommydata, components(Dropdown, evidencetable, SubmissionForm, tablecolumns, tablestyle) to the page

### CODE REVIEW

**Comment by Uniunt** [comment]
good job!

**Comment by Willedge** [comment]
I check the push list, the module is needed.

**Comment by Uniunt** [comment]
🥵🥵🥵

**Comment by gyr5098** [comment]
😃😃😃great😍

**Pull request merged**
